### ISSUE TITLE
Revisit how axon and dendrite nodes are identified

### ISSUE THREAD

**Issue by napakalas** [AnatomicMaps/map-knowledge#29]
Review of the NPO's TTL files confirms that `ilxtr:hasAxonLocatedIn` and `ilxtr:hasDendriteLocatedIn `are used to specify axons and dendrites. For example: ilxtr:neuron-type-bolew-unbranched-4:
https://github.com/SciCrunch/NIF-Ontology/blob/b6db0d85d6b0b6bc4e842ef08276039b5ab1a28b/ttl/generated/neurons/apinat-simple-sheet.ttl#L1369C1-L1393C42
The current code should use this partonomy and avoid `ilxtr:hasSomaLocatedIn`, `ilxtr:hasAxonPresynapticElementIn`, `ilxtr:hasAxonSensorySubcellularElementIn`, and `ilxtr:hasAxonLeadingToSensorySubcellularElementIn`.

**Comment by dbrnz** [comment]
Thanks.

It though still would be useful to record `ilxtr:hasSomaLocatedIn` as a `somas` property of a neuron path, similar to `dendrites` and `axons`.

**Comment by napakalas** [comment]
I'll add that.
Additionally, some somas, axons, and dendrites are found to be unavailable in the corresponding neuron population, so they are filtered out.

**Comment by dbrnz** [comment]
> Additionally, some somas, axons, and dendrites are found to be unavailable as nodes in the corresponding neuron population, so they are filtered out.

In what way are nodes not available? I understood that we start with a set of nodes that make up a neuron population and these nodes have various classifications.

How does using `ilxtr:hasAxonLocatedIn` compare with the previous way of identifying axons? Have you compared old and new sets of axons over all neuron populations? To me, it would make sense if the new axon set was a superset of the old set, but it would be good to confirm this.

**Comment by napakalas** [comment]
As an example, in ilxtr:neuron-type-keast-8, there is an axon specified as:
[ 
          a owl:Restriction ;
          owl:onProperty ilxtr:hasAxonLocatedIn ;
          owl:someValuesFrom 
          [ 
                   a owl:Restriction ;
                   owl:onProperty partOf: ;
                   owl:someValuesFrom UBERON:0002318 
          ]
 ]
However, `UBERON:0002318` is not used in any nodes. In this case, this axon is removed.

The use of ilxtr:hasAxonLocatedIn is consistent with other partonomies, such as ilxtr:hasAxonPresynapticElementIn. After checking all populations, most of the new axons are not supersets of the old ones.

**Comment by napakalas** [comment]
It seem like, I did a mistake when comparing the new axon to the old one. I am rechecking now.

**Comment by dbrnz** [comment]
It would be useful to understand why `keast-8` has an axon in `UBERON:0002318` but `UBERON:0002318` isn't a path node. Presumably there is some node that is `part-of` UBERON:0002318 -- maybe worth asking on the K-Core Slack channel.

And also to ask K-Core what the differences are between the different axon properties...

**Comment by dbrnz** [comment]
Closed by PR #32.
