### ISSUE TITLE
Resolves axon nodes based on specified predicates

### ISSUE THREAD

**Issue by napakalas** [AnatomicMaps/map-knowledge#31]
As discussed, axon nodes are identified using the following four predicates:

- `ilxtr.hasAxonPresynapticElementIn`
- `ilxtr.hasAxonSensorySubcellularElementIn`
- `ilxtr.hasAxonLeadingToSensorySubcellularElementIn`
- `ilxtr.hasAxonLocatedIn`

Need to update current code which only uses `ilxtr.hasAxonLocatedIn`

**Comment by dbrnz** [comment]
Closed by PR #32.
